name: TipMessages
version: '${project.version}'
main: me.liamsnow.tipmessages.TipMessages
api-version: 1.19
authors: [ LiamSnow ]
website: https://liamsnow.com
depend: []
softdepend: []
commands:
  tipmessages-reload:
    description: Reloads the TipMessages config & messages
    usage: /<command>
    aliases: [ tm-reload ]
    default: op
  tipmessages-force:
    description: Force sends a message to all players
    usage: /<command>
    aliases: [ tm-setspawn ]
    default: op